---
- name: Run role
  hosts: all
  become: true
  any_errors_fatal: true

  roles:
    - role: ansible-system_grub

  vars:
    grub_timeout: 5
    grub_recordfail_timeout: "5"
    grub_cmdline: "ipv6.disable=1 apparmor=1 security=apparmor"
    grub_add_filed:
      - file: 01_passwd
        value: |
          set superusers='root' password_pbkdf2 root grub.pbkdf2.sha512.10000.7C6DC0B6EA14D77D91C260C7410EDD5DF807295BE94284911EEB9C44BBAC0DD86B5606CC8C89BCB3FF4D91F39CDBF091B7C8923372B95BABB7170507D7AED9E6.D6F0E45D0B978919786C1BBAC888E8E38EEE28B454BCC93008D314974F7788C8E4C614C090862CEA4AFA841493131BDC8CD3642E8034F2C542FD87ADFB574797
      - file: 10_linux
        regex: "CLASS="
        value: "--unrestricted"
