---

- name: Test if grub_timeout is set correctly
  ansible.builtin.assert:
    that:
      - grub_timeout is number
      - grub_timeout >= 0
    quiet: true
  when:
    - grub_timeout is defined

- name: Test if grub_recordfail_timeout is set correctly
  ansible.builtin.assert:
    that:
      - grub_recordfail_timeout is number
      - grub_recordfail_timeout >= 0
    quiet: true
  when:
    - grub_ecordfail_timeout is defined

- name: Test if grub_add_cmdline is set correctly
  ansible.builtin.assert:
    that:
      - grub_add_cmdline is iterable
    quiet: true
  when:
    - grub_add_cmdline is defined

- name: Test if item in grub_add_cmdline is set correctly
  ansible.builtin.assert:
    that:
      - item.option is defined
      - item.option is string
      - item.value is defined
    quiet: true
  loop: "{{ grub_add_cmdline }}"
  loop_control:
    label: "{{ item.option }}"
  when:
    - grub_add_cmdline is defined
